### ISSUE TITLE
Docs don't match code

### ISSUE THREAD

**Issue by gaxweb** [huytdq94/sw-example-plugin-flow-builder#3]
https://developer.shopware.com/docs/guides/plugins/plugins/framework/flow/add-flow-builder-action

If I follow that howto, the Flow Builder doesn't show an action label. The example plugin works.

I've tried a few things and I've found that simply deleting the file `custom/plugins/sw-example-plugin-flow-builder-master/src/Resources/public/administration/js/example-plugin.js` will produce the same problem - the action label stops showing up. That looks like a generated file and probably shouldn't be in this repo. I certainly have no idea how I'm supposed to generate it.

The tutorial also doesn't mention that you have to create the `custom/plugins/sw-example-plugin-flow-builder-master/src/Resources/app/administration/src/snippet/*` files for translation.

So either the docs are incomplete or there are files in the repository that aren't explained in the docs. As is, I can't create a working Flow plugin.

**Comment by nguyenquangtin** [comment]
@gaxweb 
Please use the cli `❯ ./psh.phar storefront:build` in folder development to rebuild the plugin. It will re-generate the code of your plugin, and it should make your plugin work as expected.

Hope this can help you. Please let me know again if you couldn't make it.

**Comment by gaxweb** [comment]
> in folder development

What do you mean by that? I've run it from the shopware root dir and it didn't create said file, not even in the example plugin. I'm using SW v6.4.14.0

**Comment by nguyenquangtin** [comment]
@gaxweb 
Please follow this guide - https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-custom-javascript#testing-your-changes

Run the cli as 
### development 
`./psh.phar storefront:build`

### production template 
`./bin/build-storefront.sh`

**Comment by gaxweb** [comment]
That's what I did, but it didn't create that .js file. The only error I got was 1 deprecation error during template generation, other than that it was "successful":

            08:22:32 INFO      [php] User Deprecated: Since shopware/core : Class Shopware\Storefront\Event\ThemeCompilerEnrichScssVariablesEvent is deprecated. Use Shopware\Storefront\Theme\Event\ThemeCompilerEnrichScssVariablesEvent instead.
        
            #file: "./vendor/shopware/platform/src/Core/Framework/Feature.php"
            #line: 148

**Comment by nguyenquangtin** [comment]
The deprecated warning should not be an issue. I also got that.  If you see this message after that, then your plugin should be built. 

```
Duration: 6s
All commands successfully executed!
```

Or you can try to clear the cache system and build it again.

**Comment by gaxweb** [comment]
It doesn't work. If I download the ZIP of the current master branch version, extract the files in the `custom/plugin` folder, delete the `example-plugin.js` file and then install and enable the plugin, that JS file will not be generated. Running the command you posted afterwards doesn't cause the file to be created either.

Are you saying you did the same thing and for you it worked?

Edit: Duh… I had to run `./psh.phar administration:build`, of course. But that's not mentioned in the tutorial either. I had assumed that switching the plugin on and off would be enough. Apparently not.
